# Generated by Codex on 2026-02-18
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('poll', 'Poll'), ('push', 'Push')], max_length=16)),
                ('protocol', models.CharField(choices=[('modbus', 'Modbus'), ('opcua', 'OPC UA'), ('mqtt', 'MQTT')], max_length=16)),
                ('endpoint', models.JSONField(default=dict)),
                ('poll_interval_sec', models.IntegerField(blank=True, null=True)),
                ('timeout_sec', models.IntegerField(default=60)),
                ('mapping', models.JSONField(default=dict)),
            ],
        ),
    ]
